### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Eduardo-Vieira** [lukasdev/DRouter#5]
Achei bem legal o seu mini api mas fata ele usar o COSR 

header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");

para uso do angular 2 e ionic

**Comment by lukasdev** [comment]
Não vejo por que isso seria necessário PARA o DRouter. Visto que você pode criar sua aplicação usando o Cross Origin nas rotas individuais.

**Comment by Eduardo-Vieira** [comment]
se você for ver o slim PHP ele tem uma função no core dele para ativar o recurso.
