### ISSUE TITLE
Erro ao Executar Middlewares apartir de uma String

### ISSUE THREAD

**Issue by JonatanFlores** [lukasdev/DRouter#6]
Quando eu tento aplicar uma classe de middleware em uma rota não está sendo feita a instância da classe em um objeto. Sendo retornada a seguinte mensagem:

**Fatal error: Using $this when not in object context in /var/www/dadus.erp/app/middlewares/JwtAuthMiddleware.php**

Minha classe de Middleware **JwtAuthMiddleware** (incompleta): 

```php
<?php

namespace App\Middlewares;

use DRouter\Middlewares\MiddlewareInterface;

class JwtAuthMiddleware implements MiddlewareInterface
{
    public function handle($request, $response, \Closure $next)
    {
        $this->getHeaders();

        return $next($request, $response);
    }

    /**
     * Retorna um array contendo todos os headers ou entao o
     * valor de um unico header, caso tenha sido informado
     * o parametro contendo o nome do mesmo.
     *
     * @param null|mixed $header
     */
    protected function getHeaders($header = null)
    {
        $headers = apache_request_headers();

        if (null === $header) {
            return $headers;
        }

        return isset($headers[$header]) ? $headers[$header] : false;
    }
}
```
Meu arquivo de rota, **routes.php**: 

```php
<?php

$app->group('/api/v1', function() use ($app) {
    $app->get('/produtos', 'App\Controllers\Api\ProdutoController:index');
})->add(App\Middlewares\JwtAuthMiddleware::class);
```

**Comment by lukasdev** [comment]
Opa, olá Jonatan. Desculpe não ter respondido antes :'(
Estou com tanta coisa na cabeça esse mes que mal tive tempo de entrar no github.
Olhando por cima aqui seu erro e sua mensagem, notei que vc passou o caminho ::class do seu middleware, não me lembro de ter implementado em puxando em contexto de classe o MIddleware :| ... Funcionaria com certeza se vc passasse a instancia.
Enfim, vi aqui que vc mandou um pull request, vou ler la!
